---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
spec:
  id: my-db
  compositionSelector:
    matchLabels:
      provider: google
      db: postgresql
  parameters:
    version: "15"
    size: medium
    databases:
      - my-db
    secrets:
      storeName: google
      pullRootPasswordKey: db-password
      pushToStore: true
      pullToCluster: a-team-cluster
      pullToClusterNamespace: production
